version: "3.9"

services:
  db:
    image: library/postgres:13
    container_name: persons_db
    restart: on-failure
    environment:
      POSTGRES_DB: "persons_db"
      POSTGRES_USER: "moderator"
      POSTGRES_PASSWORD: "2222"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    networks:
      - persons-network
    ports:
      - "5432:5432"

  api:
    image: persons_api
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: persons_api
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./configs/api.yaml:/configs/api.yaml
    networks:
      - persons-network

volumes:
  db-data:

networks:
  persons-network:
    name: persons_network
    driver: bridge
